### ISSUE TITLE
Partial Update for e-ink display

### ISSUE THREAD

**Issue by r00sta** [pauls-3d-things/esp8285m3_smartwatch#1]
Most of the e-ink modules available on ebay etc support partial refresh which require less power and are sub 1s.
Here is a library that supports it - https://github.com/ZinggJM/GxEPD
I can't find the original webpage that I saw with an example second counter but will post it if/when I do find it.

**Comment by uvwxy** [comment]
Thank you for the link. I took a look at the library and decided to stay with u8g2. See the update in the readme section, on how to enable partial refresh with u8g2 😄.

The reason to stay with u8g2 is, it supports way more display (portability) and has more fonts.

**Comment by uvwxy** [comment]
But I'm tending to draw without the partial refresh, to get better image quality.
